### ISSUE TITLE
Conflict with REI's disable recipe book

### ISSUE THREAD

**Issue by lizfinite** [briansemrau/Cosmetic-Armor-Slots#1]
Hello. 
Tried to download and install your mod; everything went as normal and it appeared in mod menu but I could not find an entry in the controls section to open the cosmetic armor slots GUI.
I thought it might be conflicting with another mod, maybe fabric controlling specifically since that allows you to search controls, etc. But everything else custom was appearing fine, so I tested your mod in a fresh instance with only itself (1.0.0 from CurseForge), Fabric API (0.3.0+build.185) and the most recent loader/mappings (0.4.8+build.155 and 1.14.2+build.7) and had the same issues. , Pressing all keys on my keyboard did not produce the GUI, either. I did not however, try unbind default keys.
However, when adding Mod Menu; I can see that the mod is loaded, at least to the point that mod menu pretends it's there. 
![2019-06-18_07 58 23](https://user-images.githubusercontent.com/36245622/59684327-5eee1680-919f-11e9-9cf2-b05285a617e2.png)

The log seems rather uneventful to me, but maybe it will be of use to you. I loaded into a world briefly to see if it would produce any out of place output but noticed nothing.
https://pastebin.com/0PtRLKj5

Let me know if there's anything else I can provide to narrow down the issue. Excited to see more well-known modded features like this brought to Fabric .

**Comment by briansemrau** [comment]
There is no keyboard button to open the GUI. There should be a small golden boots icon in your inventory screen to open it. Let me know if that works. If that's the problem, I'll update the mod description to make this clear.

**Comment by lizfinite** [comment]
If it was a snake it would've bitten me, damn. Completely glossed over it. 
But... now there's another... strange issue that I'm gonna have to test further...

It seems that when I added it to my Mod Pack instance I've been using, it doesn't appear in the GUI next to the player. I tried removing resource packs but was unsure why that would have an effect. It didn't make the button appear when I did. 

However, copying all of the exact same mods to a fresh instance with fresh configuration and no resourcepacks does seem to let it appear... Even loaded up the same world to see if it was somehow wonky but I was also pretty unsure that should actually make a difference... 
Here's my original pack I usually add to:
![2019-06-18_18 26 18](https://user-images.githubusercontent.com/36245622/59726374-f03ca780-91f6-11e9-86f3-d2e3d20004ae.png)
![2019-06-18_18 26 24](https://user-images.githubusercontent.com/36245622/59726373-f03ca780-91f6-11e9-82ee-94a75f194425.png)
![2019-06-18_18 26 44](https://user-images.githubusercontent.com/36245622/59726372-f03ca780-91f6-11e9-9e25-c76eb43dce61.png)

And here's the fresh one:
![2019-06-18_18 27 37](https://user-images.githubusercontent.com/36245622/59726390-034f7780-91f7-11e9-8354-578191f1f2a2.png)
![2019-06-18_18 27 44](https://user-images.githubusercontent.com/36245622/59726389-034f7780-91f7-11e9-8234-0b376876b004.png)
![2019-06-18_18 27 59](https://user-images.githubusercontent.com/36245622/59726388-034f7780-91f7-11e9-94de-8bd4a9aadeef.png)

After copying the configuration files over to the new instance, the problem has started occurring there too. Very perplexing. 
I'll have to keep investigating and open another issue if I narrow down the conflict. 
Otherwise, it seems to be working as intended.

**Comment by lizfinite** [comment]
So, I narrowed down the problem of the button not appearing at all to using REI's "disable recipe book" module. 
My guess would be he modifies the GUI in some way that your button does not get assigned to it anymore; as it doesn't seem to just be invisible, the bottom right area is non-functional as well.
Maybe his module for disabling the recipe is essentially a clone of the regular GUI without the recipe book code and he just disables the normal one and redirects to his edited code; so your mod no longer displays because it's mixin modifies the default GUI. While his module opens another, self-defined GUI. 

That's my serious amount of arm chair development guess. Could be completely off base. For now not enabling that option fixes this conflict.

**Comment by briansemrau** [comment]
I really appreciate you narrowing down the issue. I'll take a look at it when I get the chance.

**Comment by briansemrau** [comment]
I looked at REI's code and the issue is on their end. They disable all buttons in the inventory screen. I'm submitting an issue on their repository.
