### ISSUE TITLE
Not working with Villager hats mod

### ISSUE THREAD

**Issue by calloatti** [briansemrau/Cosmetic-Armor-Slots#2]
https://github.com/Lemonszz/villager-hats/releases/tag/1.14-1.0.0

cosmetic-armor-slots-1.0.0.jar

![image](https://user-images.githubusercontent.com/12817862/59795609-0196ba00-92b2-11e9-8ab4-2c8652eb7e9a.png)
![image](https://user-images.githubusercontent.com/12817862/59795665-1d01c500-92b2-11e9-8e78-85ffc4106ca9.png)

**Comment by briansemrau** [comment]
Looks like a compatibility issue with how the player renders different features. I'm not sure if this will require the creation of an API to solve this, or if I can add some fancy way of detecting armor-like features that draw over the player.

**Comment by briansemrau** [comment]
Fixed by commit [435985b10016cd3911dc56abbd48400b69d22b9a](https://github.com/briansemrau/Cosmetic-Armor-Slots/commit/435985b10016cd3911dc56abbd48400b69d22b9a).
