### ISSUE TITLE
Server Crash on Startup with v1.1.0

### ISSUE THREAD

**Issue by lizfinite** [briansemrau/Cosmetic-Armor-Slots#3]
After looking at the logs, I discovered and reproduced the crash in a newly created test server with the latest server installer. (0.5.0.30)

The start of the error that pointed me to test just your mod and Fabric API:
`[01:05:12] [main/FATAL]: Mixin apply failed cosmeticarmorslots.mixins.json:PlayerEntityMixin -> net.minecraft.class_1657: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpected NullPointerException whilst applying the mixin class: null`

Here's the rest of the log if it helps: 
https://pastebin.com/DXLfKGhE

**Comment by briansemrau** [comment]
Shoot, I just saw this issue now. I'll get it fixed asap.

**Comment by briansemrau** [comment]
Fixed in latest release.
