### ISSUE TITLE
When opening a game to LAN, the mod does not work for other players

### ISSUE THREAD

**Issue by calloatti** [briansemrau/Cosmetic-Armor-Slots#4]
1.1.0-MC1.14.2

If you open a game to lan, the mod has no effect on how other players see you. Both clients have the mod installed.

How I see myself:
![2019-06-25_14 59 15](https://user-images.githubusercontent.com/12817862/60121633-e9afb200-9759-11e9-9d35-ab24eb9029fd.png)

How the other player sees me:
![2019-06-25_14 59 19](https://user-images.githubusercontent.com/12817862/60121712-0c41cb00-975a-11e9-9821-36d3727f9b4f.png)

**Comment by briansemrau** [comment]
This will be fixed within the day.

**Comment by briansemrau** [comment]
I missed an important piece of code that is needed to make this work on servers. It might take some time to be fixed.

**Comment by briansemrau** [comment]
Fixed in latest release.
