### ISSUE TITLE
Temp Item Duping Client Side

### ISSUE THREAD

**Issue by supersaiyansubtlety** [briansemrau/Cosmetic-Armor-Slots#8]
When I test this on my server, i frequently have items I equip to cosmetic slots reappear under my cursor as though I've clicked them, but they are also in the cosmetic slot. It's much like a type of server lag where you put an item in an inventory but it remains attached to your cursor for a second, except that the item both in the cosmetic slot and attached to the cursor. Disconnecting and reconnecting puts the item back in my inventory. 
I have the mod installed on client and server with Fabric 0.4.8 build 158 on MC 1.14.4

**Comment by briansemrau** [comment]
I'm about to release v1.1.5 that fixes a crash on startup for dedicated servers. Could you try it out? I've been poking at networking code trying to get the mod to work as intended and I don't know if the new changes will mess with what you're experiencing.

If you can still reproduce the issue, could you give me server and client logs?

**Comment by supersaiyansubtlety** [comment]
Updated to 1.1.5 and same thing's happening. I tested with no other mods or datapacks running.
Client log:
[latest.log](https://github.com/briansemrau/Cosmetic-Armor-Slots/files/3463066/latest.log)
Server log:
[latest.log](https://github.com/briansemrau/Cosmetic-Armor-Slots/files/3463067/latest.log)

**Comment by supersaiyansubtlety** [comment]
Apologies, I was having an issue unrelated to this mod that was causing it to not actually load server-side.
